### ISSUE TITLE
Would you consider releasing PSAuthClient under the MIT license?

### ISSUE THREAD

**Issue by mvarblow** [alflokken/PSAuthClient#1]
Hi. Thanks for developing this library and posting it on the PowerShell Gallery! I've found it very useful for automating some workflows with calls to APIs that are part of our commercial software application. Our APIs are authenticated against an OAuth 2.0 identity provider.

I had already scripted the certificate auth flow and was considering how to implement the interactive flow when I ran across PSAuthClient on the PowerShell Gallery. PSAuthClient worked perfectly for me, handling both flows with no problems. Thank you for that. 

I'd like to be able to share these automation scripts with our clients, but I'm concerned that the GPL license for PSAuthClient may not allow it. Would you consider releasing PSAuthClient under the MIT license?

**Comment by alflokken** [comment]
Hi, Glad to hear you've found it useful. I've updated the license to MIT on GitHub. No new release just yet, but you're free to use the source code under MIT now. =)

**Comment by mvarblow** [comment]
Thanks!
