### ISSUE TITLE
WebView2 dialog does not prompt the user for the account to authenticate as

### ISSUE THREAD

**Issue by f0oster** [alflokken/PSAuthClient#6]
When attempting the authorization code grant flow, the WebView2 window does not prompt the user to select which account to sign in as. 
```
$authorization_endpoint = "https://login.microsoftonline.com/$Tenant/oauth2/v2.0/authorize"
$token_endpoint = "https://login.microsoftonline.com/$Tenant/oauth2/v2.0/token"

$splat = @{
    client_id = $ClientId
    scope = $Scopes
    redirect_uri = "https://login.microsoftonline.com/common/oauth2/nativeclient"
}
$code = Invoke-OAuth2AuthorizationEndpoint -uri $authorization_endpoint @splat -usePkce:$false -Verbose 
```

After running the above, a WebView2 window opened and it automatically logged in without any prompt for which account to use.

I expected a prompt with a listing of the various saved users and to see the the "Use another account" option when the WebView2 window opened. In my case, I have multiple credentials for numerous accounts that I need to be able to authenticate as.

If I cancel the login before it is able to complete, I get directed back to the login screen, which is the view I was expecting to be greeted with. This view contains a list of users and the "Use another account" option is visible. 

At first I thought the account was being determined using IWA or some sort of AD/AAD SSO as it matched my windows user account (I'm authenticating to Entra ID from a domain bound host), but further testing suggests that it selects the most recently used credential on launch. 

After cancelling sign on, I was able to manually authenticate with another user. When running the module again, it defaulted to automatically signing in as the user that I most recently manually authenticated with.

**Comment by alflokken** [comment]
No worries, glad to hear it's working now! 😄
